language: node_js
node_js:
  - 'lts/*'

script:
  - yarn build

cache:
  yarn: true

deploy:
  - provider: npm
    email: $email
    api_key: $api_key
    on:
      branch: master

  - provider: pages
    skip-cleanup: true
    local_dir: dist
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    file_glob: true
    file: src/plugins/jsonschema2jsdoc.js
    on:
      tags: true